### ISSUE TITLE
Camel case?

### ISSUE THREAD

**Issue by wemoveon2** [InterwebAlchemy/model-metadata-central#1]
i like the idea of a standardized model metadata spec, but given that a lot of the model handling tends to happen in python, i think `snake_case` should be the standard instead of `camelCase`.

**Comment by ericrallen** [comment]
That’s probably a good call. My inner JavaScript developer just thinks in camelCase.

I’ll get things converted over.

**Comment by ericrallen** [comment]
This has been updated.
